<div class="modal fade" id="termsModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body" style="height: 200px; overflow-y:auto;">
          If you create an account on the Website, you are responsible for maintaining the security of your account, and you are fully responsible for all activities that occur under the account and any other actions taken in connection with the account. You agree to provide and maintain accurate, current and complete information, including your contact information for notices and other communications from us and your payment information. You may not use false or misleading information in connection to your account, or trade on the name or reputation of others, and Monargo doo – Urban One may change or remove any information that it considers inappropriate or unlawful, or otherwise likely to expose Monargo doo – Urban One to claims of third parties. You agree that we may take steps to verify the accuracy of information you have provided to us.
You are responsible for taking reasonable steps to maintain the confidentiality of your username and password. You must immediately notify Monargo doo – Urban One of any unauthorized uses of your information, your account or any other security breaches. Monargo doo – Urban One will not be liable for any acts or omissions by you, including any damages of any kind incurred as a result of such acts or omissions.

Configurations and prices of the Website, Products, and/or Services are subject to change at any time, and Monargo doo – Urban One shall at all times be entitled to modify configurations, fees, prices and quotations, provided that no price changes shall be made applicable to you during a subscription term, and shall only take effect after Monargo doo – Urban One and you have agreed upon an extension, upgrade or renewal of the subscription term. You agree to any such changes if you do not object in writing to Monargo doo – Urban One within seven (7) business days of receiving a notice of Monargo doo – Urban One, or an invoice, incorporating or announcing the fee and/or price changes. All prices are exclusive of, and you shall pay all taxes, duties, levies or fees, or other similar charges imposed on Monargo doo – Urban One or yourself by any taxing authority (other than taxes imposed on Monargo doo – Urban One income), related to your order, unless you have provided Monargo doo – Urban One with an appropriate resale or exemption certificate for the delivery location, which is the location where the Products and/or Services are used or performed. In case of changes in law such that a tax is levied that is or becomes irrecoverable with a consequent increase to the costs to Monargo doo – Urban One of delivering the Products and/or Services, whereby and to such an extent Monargo doo – Urban One is entitled to increase its prices accordingly and retroactively.

If you have purchased a product that you believe to be defective (damaged or simply does not match the product you ordered), you can report the defect within two days of delivery. To exercise these rights, you must notify us in writing of the deficiency at buy@urbanone.me with a detailed description and a picture of the deficiency.
Shipping costs are borne by the buyer. If the material defect is justified, the shipping costs will be compesated to the customer. The buyer will be notified of the resolution of the complaint within eight days of receipt of the product, and the product will be replaced with a correct one or, if agreed differently, money will be returned to the account. Once you order and pay for a product, cancellation is only possible within the same day by notifying us at buy@urbanone.me. In this case you will receive a confirmation mail and the money will be returned to your account.

We implement a number of technical and organizational measures to ensure the protection of personal data during collection, transfer and storage. Monargo doo – Urban One endeavors to appropriately protect your personal information, but does not guarantee the complete security of the personal information you provide to us and is not responsible for the theft, destruction, loss, intentional or unintentional disclosure of your personal information or information about you. Monargo doo – Urban One adheres to generally accepted standards for the protection of information received during transmission as well as after receipt, but no electronic transmission or storage is 100% secure, so we cannot guarantee complete security. Monargo doo – Urban One uses SSL technology (Secure Sockets Layer) to secure the encryption of personal and credit card information. Monargo doo – Urban One cooperates with a company that ensures the security of our services and your personal information. Monargo doo – Urban One users are additionally protected by changing the firewall and other technologies to ensure data protection.

Data protection is the responsibility of the user with appropriate protection of his or her mobile device or computer, as well as protection of the username, password and appropriate software (antivirus) protection of your electronic device. To ensure that these measures are effective in preventing unauthorized access to your personal information, you must be aware of the security features available to you through your browser. Use a browser that provides security feature settings before you submit your personal or credit card information online. Please note that if you use a browser that does not support SSL technology, such transfer of personal data may be risky.

        </div>
        <div class="modal-footer">
          <button type="button" class="" style="    width: 35%;
          border: none;
          border-radius: 5px;
          background: #231F20;
          color: white;
          padding: 5px;" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>